# Generated by Django 5.1.1 on 2024-09-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artefacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('tipo_artefacto', models.CharField(choices=[('requerimiento', 'Especificación de Requerimientos'), ('caso_uso', 'Diagramas de Casos de Uso'), ('prototipo', 'Prototipos'), ('plan_proyecto', 'Plan de Proyecto'), ('documentacion_tecnica', 'Documentación Técnica'), ('reporte', 'Reportes de Progreso'), ('manual_usuario', 'Manual de Usuario'), ('documentacion_mantenimiento', 'Documentación de Mantenimiento')], max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('autor', models.CharField(max_length=100)),
            ],
        ),
    ]
